# Documentation: https://roots.io/trellis/docs/mail/
mail_smtp_server: smtp.mandrillapp.com:587
mail_admin: admin@example.com
mail_hostname: reviewexchange.com
mail_user: WaveCloudCorp
mail_password: "{{ vault_mail_password }}" # Define this variable in group_vars/all/vault.yml
